name: Spring Boot CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout source code
        uses: actions/checkout@v4

      - name: ☕ Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: 🧪 Build with Maven
        run: mvn clean install --batch-mode

      - name: ✅ Run Unit Tests
        run: mvn test

      - name: 📦 Package App
        run: mvn package -DskipTests

      - name: 🧹 Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Optional: Upload JAR as artifact
      - name: 📤 Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
